@jwt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTM3NDM2NiwiZXhwIjoxNzM5Mzc3OTY2fQ.JtWSSgBZyKT6g3pDDMoJOon9IbqUmawmXd06waZbh5Q

POST http://localhost:5000/api/user/add
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "DNI": "27485964",
    "nombres": "Pepe Cardenas",
    "email": "pepe@gmail.com",
    "password": "Hola1234*",
    "telefono": "955778067",
    "rol": "admin"
}
###

GET http://localhost:5000/api/user/3
Authorization: Bearer {{jwt_token}}
###

PUT http://localhost:5000/api/user/3
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "DNI": "77332212",
    "telefono": "956843320",
    "email": "pepe@gmail.com"
}
###

GET http://localhost:5000/api/user/
Authorization: Bearer {{jwt_token}}
###

GET http://localhost:5000/api/user/inactives
Authorization: Bearer {{jwt_token}}

###
PATCH http://localhost:5000/api/user/deactivate/1
Authorization: Bearer {{jwt_token}}

###
PATCH http://localhost:5000/api/user/activate/1
Authorization: Bearer {{jwt_token}}

###
PATCH http://localhost:5000/api/user/delete/1
Authorization: Bearer {{jwt_token}}

